--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Material; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Material" (
                                   id bigint NOT NULL,
                                   user_id bigint NOT NULL,
                                   "materialType_id" bigint NOT NULL,
                                   name text NOT NULL,
                                   description text NOT NULL,
                                   "creationDate" date NOT NULL
);


ALTER TABLE public."Material" OWNER TO postgres;

--
-- Name: MaterialType; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MaterialType" (
                                       id bigint NOT NULL,
                                       name text NOT NULL,
                                       description text NOT NULL,
                                       extension text NOT NULL
);


ALTER TABLE public."MaterialType" OWNER TO postgres;

--
-- Name: MaterialType_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MaterialType" ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."MaterialType_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: Material_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Material" ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Material_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: authentication_codes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_codes (
                                             id bigint NOT NULL,
                                             code character varying(255) NOT NULL,
                                             expirydate timestamp(6) without time zone NOT NULL,
                                             userid bigint NOT NULL
);


ALTER TABLE public.authentication_codes OWNER TO postgres;

--
-- Name: authentication_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.groups (
                               idgroup bigint NOT NULL,
                               name character varying(255) NOT NULL,
                               description character varying(255),
                               date_created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
                               date_creation timestamp(6) without time zone
);


ALTER TABLE public.groups OWNER TO postgres;

--
-- Name: groups_idgroup_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.groups_idgroup_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.groups_idgroup_seq OWNER TO postgres;

--
-- Name: groups_idgroup_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.groups_idgroup_seq OWNED BY public.groups.idgroup;


--
-- Name: groupuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.groupuser (
                                  group_id bigint NOT NULL,
                                  user_id bigint NOT NULL
);


ALTER TABLE public.groupuser OWNER TO postgres;

--
-- Name: interest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interest (
                                 id bigint NOT NULL,
                                 name character varying(255) NOT NULL,
                                 parent_interest_id bigint
);


ALTER TABLE public.interest OWNER TO postgres;

--
-- Name: interests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.interest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: material; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.material (
                                 id bigint NOT NULL,
                                 creationdate date NOT NULL,
                                 description character varying(255) NOT NULL,
                                 location character varying(255),
                                 name character varying(255) NOT NULL,
                                 materialtype_id bigint NOT NULL,
                                 user_id bigint NOT NULL,
                                 tags character varying(255)
);


ALTER TABLE public.material OWNER TO postgres;

--
-- Name: material_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.material ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.material_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: materialtype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.materialtype (
                                     id bigint NOT NULL,
                                     description character varying(255) NOT NULL,
                                     extension character varying(255) NOT NULL,
                                     name character varying(255) NOT NULL
);


ALTER TABLE public.materialtype OWNER TO postgres;

--
-- Name: materialtype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.materialtype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materialtype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification (
                                     id bigint NOT NULL,
                                     content character varying(255),
                                     is_read boolean NOT NULL,
                                     notification_type_id bigint NOT NULL,
                                     "time" timestamp(6) without time zone NOT NULL,
                                     title character varying(255) NOT NULL,
                                     user_id bigint NOT NULL
);


ALTER TABLE public.notification OWNER TO postgres;

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: notification_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification_type (
                                          id bigint NOT NULL,
                                          name character varying(255) NOT NULL
);


ALTER TABLE public.notification_type OWNER TO postgres;

--
-- Name: notification_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review (
                               id bigint NOT NULL,
                               material_id bigint,
                               rating character varying(255),
                               description character varying(255),
                               created_at date
);


ALTER TABLE public.review OWNER TO postgres;

--
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
                               id bigint NOT NULL,
                               username character varying(255) NOT NULL,
                               passwordhash character varying(255) NOT NULL,
                               firstname character varying(255),
                               lastname character varying(255),
                               email character varying(255),
                               phonenumber character varying(255),
                               active boolean DEFAULT true NOT NULL,
                               settings character varying(255),
                               phone_number character varying(255)
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- Name: user_interest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_interest (
                                      user_id bigint NOT NULL,
                                      interest_id bigint NOT NULL
);


ALTER TABLE public.user_interest OWNER TO postgres;

--
-- Name: userinterest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.userinterest (
                                     userid bigint NOT NULL,
                                     interestid bigint NOT NULL
);


ALTER TABLE public.userinterest OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              email character varying(255),
                              firstname character varying(255),
                              lastname character varying(255),
                              passwordhash character varying(255) NOT NULL,
                              passwordsalt character varying(255) NOT NULL,
                              phonenumber character varying(255),
                              username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: users_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: groups idgroup; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groups ALTER COLUMN idgroup SET DEFAULT nextval('public.groups_idgroup_seq'::regclass);


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: postgres
--


ALTER TABLE ONLY public."MaterialType"
    ADD CONSTRAINT "MaterialType_pkey" PRIMARY KEY (id);


--
-- Name: Material Material_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Material"
    ADD CONSTRAINT "Material_pkey" PRIMARY KEY (id);


--
-- Name: authentication_codes authentication_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_codes
    ADD CONSTRAINT authentication_tokens_pkey PRIMARY KEY (id);


--
-- Name: groups groups_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_name_key UNIQUE (name);

CREATE UNIQUE INDEX users_username_key ON "user" (username);
CREATE UNIQUE INDEX users_phonenumber_key ON "user" (phone_number);
CREATE UNIQUE INDEX users_email_key ON "user" (email);


--
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (idgroup);


--
-- Name: interest interests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interest
    ADD CONSTRAINT interests_pkey PRIMARY KEY (id);


--
-- Name: material material_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT material_pkey PRIMARY KEY (id);


--
-- Name: materialtype materialtype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materialtype
    ADD CONSTRAINT materialtype_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: notification_type notification_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification_type
    ADD CONSTRAINT notification_type_pkey PRIMARY KEY (id);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- Name: notification_type uk449twjidki79m1pxogmegv9sc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification_type
    ADD CONSTRAINT uk449twjidki79m1pxogmegv9sc UNIQUE (name);


--
-- Name: authentication_codes ukm34ypnuqbsslwl4xir8ku4cqc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_codes
    ADD CONSTRAINT ukm34ypnuqbsslwl4xir8ku4cqc UNIQUE (code);


--
-- Name: authentication_codes ukmpkn8rx16wfafh2s4abxglqr8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_codes
    ADD CONSTRAINT ukmpkn8rx16wfafh2s4abxglqr8 UNIQUE (userid);


--
-- Name: interest ukniknbu0ipih4n1x85t0g6h68; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interest
    ADD CONSTRAINT ukniknbu0ipih4n1x85t0g6h68 UNIQUE (name);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_phonenumber_key UNIQUE (phonenumber);


--
-- Name: user_interest user_interest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_interest
    ADD CONSTRAINT user_interest_pkey PRIMARY KEY (user_id, interest_id);


--
-- Name: userinterest userinterest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userinterest
    ADD CONSTRAINT userinterest_pkey PRIMARY KEY (userid, interestid);


--
-- Name: user users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: user users_phonenumber_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT users_phonenumber_key UNIQUE (phonenumber);


--
-- Name: user users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey1 PRIMARY KEY (id);


--
-- Name: user users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: interest fk6rjlhi4q7lf5wr6fae8f32bke; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interest
    ADD CONSTRAINT fk6rjlhi4q7lf5wr6fae8f32bke FOREIGN KEY (parent_interest_id) REFERENCES public.interest(id);


--
-- Name: userinterest fk7mh1l26kf86h7r8ac6lng6enw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userinterest
    ADD CONSTRAINT fk7mh1l26kf86h7r8ac6lng6enw FOREIGN KEY (userid) REFERENCES public."user"(id);


--
-- Name: userinterest fk95kro5gaddapelkpcyer7ni56; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userinterest
    ADD CONSTRAINT fk95kro5gaddapelkpcyer7ni56 FOREIGN KEY (interestid) REFERENCES public.interest(id);


--
-- Name: user_interest fk97yodomof0ffqwpnt9obp1l6c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_interest
    ADD CONSTRAINT fk97yodomof0ffqwpnt9obp1l6c FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: user_interest fkb8ln91w0i5c9g4st4qxt88nkc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_interest
    ADD CONSTRAINT fkb8ln91w0i5c9g4st4qxt88nkc FOREIGN KEY (interest_id) REFERENCES public.interest(id);


--
-- Name: material fkcwhh9m2cccryfdldsholci2p2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT fkcwhh9m2cccryfdldsholci2p2 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: material fkfcqkdexh592e5vlbuu09ifah9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT fkfcqkdexh592e5vlbuu09ifah9 FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: authentication_codes fkjmxs0lih6n0oqehs14w3hbil9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_codes
    ADD CONSTRAINT fkjmxs0lih6n0oqehs14w3hbil9 FOREIGN KEY (userid) REFERENCES public."user"(id);


--
-- Name: groupuser fklsu9iucoy9dl2d58p9uylbhjx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groupuser
    ADD CONSTRAINT fklsu9iucoy9dl2d58p9uylbhjx FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: notification fkqavim9c7an81bj6chdai5pjie; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkqavim9c7an81bj6chdai5pjie FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: notification fksrug3nupbkv5qs2s5rrsgn3cp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fksrug3nupbkv5qs2s5rrsgn3cp FOREIGN KEY (notification_type_id) REFERENCES public.notification_type(id);


--
-- Name: groupuser fktc1i8cp102quwr9ggc3kwfl9h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groupuser
    ADD CONSTRAINT fktc1i8cp102quwr9ggc3kwfl9h FOREIGN KEY (group_id) REFERENCES public.groups(idgroup);


--
-- Name: Material materialType; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Material"
    ADD CONSTRAINT "materialType" FOREIGN KEY ("materialType_id") REFERENCES public."MaterialType"(id) NOT VALID;


--
-- Name: material materialTypeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.material
    ADD CONSTRAINT "materialTypeId" FOREIGN KEY (materialtype_id) REFERENCES public.materialtype(id);


--
-- Name: review review_material_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.material(id) ON DELETE CASCADE;


--
-- Name: Material user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Material"
    ADD CONSTRAINT "user" FOREIGN KEY (user_id) REFERENCES public."user"(id) NOT VALID;


--
-- PostgreSQL database dump complete
--

